AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    ts-loop-app

Globals:
    Function:
        Timeout: 20
        Runtime: nodejs20.x
        MemorySize: 128
        CodeUri: functions/

Resources:

    LoopWorkflowTriggerFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build/trigger.lambdaHandler
            Policies:
                -   StepFunctionsExecutionPolicy:
                        StateMachineName: !GetAtt LoopWorkflow.Name
            Environment:
                Variables:
                    WORKFLOW_ARN: !Ref LoopWorkflow

    LoopFirstWorkflowFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build/first.lambdaHandler

    InvokeAsyncApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build/invoke.lambdaHandler
            Environment:
                Variables:
                    LAMBDA_FUNCTION: !Ref AsyncApiFunction
                    TABLE_NAME: !Ref CorrelationTable
            Policies:
                -   LambdaInvokePolicy:
                        FunctionName: !Ref AsyncApiFunction
                -   DynamoDBCrudPolicy:
                        TableName: !Ref CorrelationTable

    AsyncApiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build/asyncapi.lambdaHandler
            Environment:
                Variables:
                    TOPIC_ARN: !Ref SnsTopicAsyncComplete
            Policies:
                -   SNSPublishMessagePolicy:
                        TopicName: !GetAtt SnsTopicAsyncComplete.TopicName

    AsyncApiCallbackFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build/callback.lambdaHandler
            Environment:
                Variables:
                    TABLE_NAME: !Ref CorrelationTable
            Events:
                SQSEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt SqsQueueAsyncComplete.Arn
                        BatchSize: 1
                        Enabled: true
            Policies:
                -   SQSPollerPolicy:
                        QueueName: !GetAtt SqsQueueAsyncComplete.QueueName
                -   DynamoDBCrudPolicy:
                        TableName: !Ref CorrelationTable
                -   Statement:
                        -   Effect: Allow
                            Action:
                                - states:SendTaskSuccess
                                - states:SendTaskFailure
                                - states:SendTaskHeartbeat
                            Resource: !GetAtt LoopWorkflow.Arn
#
    LoopWorkflow:
        Type: AWS::Serverless::StateMachine
        Properties:
            Definition: # TODO: externalize
                StartAt: FirstWorkflowState
                States:

                    FirstWorkflowState:
                        Type: Task
                        Resource: !GetAtt LoopFirstWorkflowFunction.Arn
                        Parameters:
                            FunctionName: !GetAtt InvokeAsyncApiFunction.Arn
                        ResultPath: $.data
                        Next: InvokeAsyncApi

                    InvokeAsyncApi:
                        Type: Task
                        Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
                        Parameters:
                            FunctionName: !GetAtt InvokeAsyncApiFunction.Arn
                            Payload:
                                taskToken.$: $$.Task.Token
                        ResultPath: $.async
                        Retry: [ {
                            ErrorEquals: [ "Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException" ],
                            IntervalSeconds: 2,
                            MaxAttempts: 6,
                            BackoffRate: 2
                        } ]
                        End: true

            Policies:
                -   LambdaInvokePolicy:
                        FunctionName: !Ref LoopFirstWorkflowFunction
                -   LambdaInvokePolicy:
                        FunctionName: !Ref InvokeAsyncApiFunction
#
    CorrelationTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            PrimaryKey:
                Name: correlationId
                Type: String

    SnsTopicAsyncComplete:
        Type: AWS::SNS::Topic
        Properties:
            TopicName: ts-loop-async-complete
            Subscription:
                -   Protocol: sqs
                    Endpoint: !GetAtt SqsQueueAsyncComplete.Arn

    SqsQueueAsyncComplete:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: ts-loop-async-complete

    # Policy allows SNS to publish to this SQS queue
    SnsToSqsPolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -   Sid: "Allow SNS publish to SQS"
                        Effect: Allow
                        Principal:
                            Service: "sns.amazonaws.com"
                        Resource: !GetAtt SqsQueueAsyncComplete.Arn
                        Action: SQS:SendMessage
                        Condition:
                            ArnEquals:
                                aws:SourceArn: !Ref SnsTopicAsyncComplete
            Queues:
                -   Ref: SqsQueueAsyncComplete
